name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Write local.properties for Flutter SDK
        run: |
          echo "flutter.sdk=$(pwd)/submodules/flutter" > android/local.properties

      - name: Flutter version
        run: submodules/flutter/bin/flutter --version

      - name: Get dependencies
        run: submodules/flutter/bin/flutter pub get

      - name: Analyze
        run: submodules/flutter/bin/flutter analyze
        continue-on-error: true

      - name: Run tests
        run: submodules/flutter/bin/flutter test
        continue-on-error: true

      - name: Build APK (sanity check)
        run: submodules/flutter/bin/flutter build apk #--release

      - name: Upload APK (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          if-no-files-found: error
          retention-days: 7
          path: build/app/outputs/flutter-apk/app-release.apk