name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FLUTTER_VERSION: "latest"

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: "stable"

    - name: Get dependencies
      run: flutter pub get

    - name: Format check
      run: dart format --set-exit-if-changed lib test

    - name: Code analysis
      run: flutter analyze

    - name: Run tests
      run: flutter test

    - name: Build apk (check)
      run: flutter build apk --release